# Generated by Django 4.2.2 on 2023-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_form_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_form_time', models.TimeField()),
                ('appointment_form_full_name', models.CharField(max_length=100)),
                ('appointment_form_email', models.EmailField(max_length=254)),
                ('appointment_form_phone', models.CharField(max_length=20, null=True)),
                ('appointment_form_address', models.CharField(max_length=100)),
                ('appointment_form_message', models.TextField()),
            ],
        ),
    ]
