# Generated by Django 4.2.2 on 2023-06-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_time',
            new_name='appointment_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_address',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_full_name',
            new_name='your_address',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_email',
            new_name='your_email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_form_phone',
            new_name='your_phone',
        ),
    ]
